#!/bin/sh
set -euo pipefail
set -x

mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

mount -t tmpfs none /tmp
mount -t tmpfs none /var/run
mkdir -p /tmp/etc

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
